### PR TITLE
feat: add dipdup guide to ecosystem section in the docs

### PR DESCRIPTION
**Pull request by Wizard1209**

### CODE REVIEW

**Review by Eikix — COMMENTED** [review]
Hi thanks a lot for the PR!

Was this tested locally, does this work?

Also, about folder structure, we should make the data indexers a folder, just like the ecosystem, and nest dipdup inside of it!

**Comment by Wizard1209** [comment]
Hi @Eikix 
The entire scenario was tested locally, so yes
I made new folder Data indexers with DipDup guide, check it out

**Comment by Eikix** [comment]
Hi I just proposed a new folder structure, let me know if it's fine for you

**Comment by Wizard1209** [comment]
Great!

**Review by Eikix — APPROVED** [review]
lgtm

**Pull request merged**
