### PR TITLE
fix routes

### PR DESCRIPTION
**Pull request by naufalkharits**
to fix this::

https://github.com/kkrt-labs/kakarot-docs/assets/80172679/c4aa2416-69b3-44bd-b346-03bcb166dab6

### CODE REVIEW

**Review by Eikix — APPROVED** [review]
lgtm

**Comment by Eikix** [comment]
Can you rebase:)?

**Comment by naufalkharits** [comment]
> Can you rebase:)?

rebased

**Comment by Eikix** [comment]
Have you tried locally again if the links work?
I made a change that deleted the landing page for the docs

**Comment by Eikix** [comment]
Update: I notice that in the current state of www.kakarot.org and docs.kakarot.org the links work properly
That being said, your video allowed me to debug the kakarot.org website, since the "Explore Docs" button redirected to the wrong URL after I replaced the landing page by the quick start

**Comment by naufalkharits** [comment]
youre right, I noticed the issue when it still had `quick-start/`.
tested it again, this change shouldn't be needed anymore.

the bug is that every time a user clicks the direct link, it adds child url instead of goin directly to the page.

https://github.com/kkrt-labs/kakarot-docs/assets/80172679/a9dde714-619f-49cb-8053-87a6054b5917

**Comment by Eikix** [comment]
> youre right, I noticed the issue when it still had `quick-start/`. tested it again, this change shouldn't be needed anymore.
> 
> the bug is that every time a user clicks the direct link, it adds child url instead of goin directly to the page.
> 
>  testing.mp4

What is the difference?

**Comment by naufalkharits** [comment]
sorry I didn't make a testing video while there was still `quick-start`/.
I'll explain in plain text, hope you would get it.

before:
- `localhost/quick-start` → `survival-guide` ✅ works perfectly
- `localhost/quick-start/` → `survival-guide` ❌ it will adds child url

this pull request:
- `localhost/quick-start` → `/survival-guide` ✅ works perfectly
- `localhost/quick-start/` → `/survival-guide` ✅ works perfectly

**Comment by Eikix** [comment]
> sorry I didn't make a testing video while there was still `quick-start`/. I'll explain in plain text, hope you would get it.
> 
> before:
> 
> * `localhost/quick-start` → `survival-guide` ✅ works perfectly
> * `localhost/quick-start/` → `survival-guide` ❌ it will adds child url
> 
> this pull request:
> 
> * `localhost/quick-start` → `/survival-guide` ✅ works perfectly
> * `localhost/quick-start/` → `/survival-guide` ✅ works perfectly

But now if you've rebased it should be:

localhost and not localhost/quick-start/ right?

**Comment by naufalkharits** [comment]
> youre right, I noticed the issue when it still had `quick-start/`. tested it again, this change shouldn't be needed anymore.
> 
> the bug is that every time a user clicks the direct link, it adds child url instead of goin directly to the page.
> 
>  testing.mp4

yes 💯
As I said above, this pull request may not be needed anymore, assuming the docs web remain without a child url not like before had a child url(quick-start/).

**Comment by Eikix** [comment]
> > youre right, I noticed the issue when it still had `quick-start/`. tested it again, this change shouldn't be needed anymore.
> > the bug is that every time a user clicks the direct link, it adds child url instead of goin directly to the page.
> > testing.mp4
> 
> yes 💯 As I said above, this pull request may not be needed anymore, assuming the docs web remain without a child url not like before had a child url(quick-start/).

Thanks for the explanation 🙏. I'll close the PR for now; note this has been very helpful in finding a problem in the kakarot.org website button link so thank you.
I hope to see more PRs from you on our repos:)

**Pull request closed without merging**
